---
# tasks file for roles/nodejs
- name: Install Node.js
  dnf:
    name: nodejs
    state: present

- name: Create app directory
  file:
    path: /opt/app
    state: directory

- name: Copy app files
  copy:
    src: ../../app/
    dest: /opt/app/

- name: Install dependencies
  command: npm install
  args:
    chdir: /opt/app

- name: Copy systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Ensure app service is running
  service:
    name: app
    state: restarted
    enabled: true
